services:

  varnish:
    image: varnish:${VARNISH_VERSION:-7}
    container_name: ${VARNISH_CONTAINER_NAME:-varnish}
    restart: unless-stopped
    profiles:
      - standalone
      - cache
    volumes:
      - ./conf/varnish/drupal.vcl:/etc/varnish/drupal.vcl
    environment:
      VARNISH_HTTP_PORT: 6081
    env_file: .env
    ports:
      - 127.0.0.1:${VARNISH_PORT:-6081}:6081
    command: ${VARNISH_COMMAND}
    networks:
      customnetwork:
        ipv4_address: 192.168.1.2

  search:
    image: solr:${SOLR_VERSION:-8}
    container_name: ${SOLR_CONTAINER_NAME:-solr}
    restart: unless-stopped
    profiles:
      - search
    env_file: .env
    volumes:
      - solr-cores:/var/solr
    networks:
      customnetwork:
        ipv4_address: 192.168.1.3

  database:
    image: mariadb:${DB_CONTAINER_VERSION:-10.6}
    container_name: ${DB_CONTAINER_NAME:-database}
    restart: unless-stopped
    profiles:
      - database
      - standalone
    env_file: .env
    volumes:
      - ./conf/mariadb/90-drupal.cnf:/etc/mysql/conf.d/90-drupal.cnf
      - mariadb-databases:/var/lib/mysql
    networks:
      customnetwork:
        ipv4_address: 192.168.1.4

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  solr-cores:
  mariadb-databases:
