services:

  varnish:
    image: varnish:7
    container_name: varnish
    restart: unless-stopped
    profiles:
      - drupal
      - reverse_proxy
    volumes:
      - ./conf/varnish/drupal.vcl:/etc/varnish/drupal.vcl
    environment:
      VARNISH_HTTP_PORT: 6081

    env_file: .env
#    ports:
#      - 127.0.0.1:${VARNISH_PORT:-6081}:6081
    command: "-s malloc,4GB -p http_max_hdr=512 -p workspace_backend=196608 -p http_req_hdr_len=65536 -p http_resp_hdr_len=65535 -p http_resp_size=4194304 -p thread_pool_min=100 -p thread_pool_max=500 -p http_req_size=131072 -p workspace_client=256k"

  search:
    image: library/solr:8
    container_name: solr
    restart: unless-stopped
    profiles:
      - drupal
      - solr
    environment:
      SOLR_JAVA_MEM: "-Xms128m -Xmx2g"
    env_file: .env
    volumes:
      - solr-cores:/var/solr

  database:
    image: library/mariadb:10.6
    container_name: database
    restart: unless-stopped
    profiles:
      - database
    env_file: .env
    volumes:
      - ./conf/mariadb/90-drupal.cnf:/etc/mysql/conf.d/90-drupal.cnf
      - mariadb-databases:/var/lib/mysql

volumes:
  solr-cores:
  mariadb-databases:

